[package]
name = "flize"
version = "0.0.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/xacrimon/flize"
homepage = "https://github.com/xacrimon/flize"
description = "non global, configurable and fast concurrent resource reclamation"
readme = "README.md"
documentation = "https://docs.rs/flize"
keywords = ["atomic", "concurrent", "memory", "epoch", "reclamation"]
categories = ["concurrency", "algorithms", "data-structures"]

[dependencies]
once_cell = "1.4.0"

[target.'cfg(loom)'.dependencies]
loom = "0.3.5"
